CI format code, implementation v1

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,44 +24,20 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v2
-      - name: Check line length
+      - name: Setup the latest .NET 5 SDK
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: 5.0.x
+      - name: Code formating check
         run: |
-          $found = $false
-          Foreach ($pattern in "*.cs","*.tt") {
-            Foreach ($file in Get-ChildItem -Path Src -Filter $pattern -Recurse -File) {
-              If (-Not (($file.Directory.Name -Eq "Resources") -Or (Select-String -Path $file -Pattern "^// disable: max_line_length" -Quiet))) {
-                $index = 1
-                Foreach ($line in Get-Content $file)
-                {
-                  If ($line.Length -gt 90) {
-                    Write-Host "##[error]${file}:${index}: line too long ($($line.Length) > 90 characters)"
-                    $found = $true
-                  }
-                  $index++
-                }
-              }
-            }
-          }
-          
-          If ($found) {
-            Exit 1
-          }
-      - name: Check T4 line endings
-        run: |
-          # WORKAROUND: The TextTransform tool fails when the T4 template ends with a newline.
-          $found = $false
-          Foreach ($pattern in "*.tt","*.ttinclude") {
-            Foreach ($file in Get-ChildItem -Path Src -Filter $pattern -Recurse -File) {
-              If ((Get-Content -Raw $file) -match "\r\n$") {
-                Write-Host "##[error]${file}: Bad T4 line ending"
-                $found = $true
-              }
-            }
-          }
-          
-          If ($found) {
-            Exit 1
-          }
+          dotnet tool restore
+          dotnet jb cleanupcode "Src" "Samples" --profile="Built-in: Reformat Code" --settings="ILGPU.DotSettings" --verbosity=WARN
+          files=($(git diff --name-only))
+          if [ ${#files[@]} -gt 0 ]
+          then
+            for file in $files; do echo "::error file=$file::Code format check failed"; done
+            exit 1
+          fi
 
   # Setup the OS matrix so that CUDA tests do not run on forks, as it needs self-hosted runners.
   # Skip running on macOS in most cases.
