Promote .NET 5 to a default target framework. (#536)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,17 +3,23 @@ name: CI
 on:
   push:
   pull_request:
+  schedule:
+    # Run daily at 00:00 so we get notified if CI is broken before a pull request
+    # is submitted.
+    - cron:  '0 0 * * *'
 
 env:
   DOTNET_NOLOGO: true
 
 jobs:
+
+  # Check some basic style rules.
   check-style:
     # Do not run this job for pull requests where both branches are from the same repo.
     # Jobs that depend on this one will be skipped too.
     # This prevents duplicate CI runs for our own pull requests, whilst preserving the ability to
     # run the CI for each branch push to a fork, and for each pull request originating from a fork.
-    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
+    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
     runs-on: windows-latest
     steps:
       - name: Checkout
@@ -57,13 +63,14 @@ jobs:
             Exit 1
           }
 
-  # Setup the OS matrix so that CUDA tests do not run on forks, as it needs self-hosted runners
+  # Setup the OS matrix so that CUDA tests do not run on forks, as it needs self-hosted runners.
+  # Skip running on macOS in most cases.
   setup-os-matrix:
     # Do not run this job for pull requests where both branches are from the same repo.
     # Jobs that depend on this one will be skipped too.
     # This prevents duplicate CI runs for our own pull requests, whilst preserving the ability to
     # run the CI for each branch push to a fork, and for each pull request originating from a fork.
-    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
+    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
     runs-on: ubuntu-latest
     steps:
       - name: Setup OS matrix
@@ -75,10 +82,13 @@ jobs:
           # pushed, we do this since macOS builds last too long and ILGPU 
           # is rarely used on a macOS
           (
-            [ "${{ github.event_name }}" == "push" ] &&
+            [ "${{ github.event_name }}" == "schedule" ] ||
             (
-              [ "${{ github.ref }}" == "refs/heads/master" ] ||
-              [[ "${{ github.ref }}" =~ "refs/tags/v" ]]  
+              [ "${{ github.event_name }}" == "push" ] &&
+              (
+                [ "${{ github.ref }}" == "refs/heads/master" ] ||
+                [[ "${{ github.ref }}" =~ "refs/tags/v" ]]  
+              )
             )
           ) && os+=("macos-latest")
 
@@ -88,52 +98,85 @@ jobs:
     outputs:
       os: ${{ steps.setup-os-matrix.outputs.os }}
 
-  build-and-test:
+  # Check that building the entire solution for all target frameworks works.
+  build:
+    # Do not run this job for pull requests where both branches are from the same repo.
+    # Jobs that depend on this one will be skipped too.
+    # This prevents duplicate CI runs for our own pull requests, whilst preserving the ability to
+    # run the CI for each branch push to a fork, and for each pull request originating from a fork.
+    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
+    runs-on: windows-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Setup the latest .NET 5 SDK
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: 5.0.x
+
+      - name: Build
+        run: dotnet build --configuration=Release -p:TreatWarningsAsErrors=true Src
+
+  # Run tests for all supported combinations of OS/library/framework.
+  test:
     needs: setup-os-matrix
     strategy:
       matrix:
         os: ${{ fromJson(needs.setup-os-matrix.outputs.os) }}
         library: [ILGPU, ILGPU.Algorithms]
+        framework: [netcoreapp3.1, net5.0]
+        include:
+          - os: windows-latest
+            library: ILGPU
+            framework: net47
+          - os: windows-latest
+            library: ILGPU.Algorithms
+            framework: net47
       fail-fast: false
     runs-on: ${{ matrix.os }}
     steps:
       - name: Checkout
         uses: actions/checkout@v2
-      - name: Setup .NET Core SDK
+
+      - name: Setup the latest .NET 5 SDK
         uses: actions/setup-dotnet@v1
         with:
-          dotnet-version: 3.1.407
-      - name: Pin .NET Core SDK
-        run: dotnet new globaljson --sdk-version 3.1.407
-      - name: Release Build
-        run: dotnet build --configuration=Release -p:TreatWarningsAsErrors=true Src
-      - name: CPU Tests
-        if: matrix.os != 'cuda'
-        run: dotnet test --logger GitHubActions --no-build --configuration=Release Src/${{ matrix.library }}.Tests.CPU
-        env:
-          ILGPU_CLEAN_TESTS: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) }}
-      - name: CUDA Tests
-        if: matrix.os == 'cuda'
-        run: dotnet test --logger GitHubActions --no-build --configuration=Release Src/${{ matrix.library }}.Tests.Cuda
-        env:
-          ILGPU_CLEAN_TESTS: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')) }}
+          dotnet-version: 5.0.x
+      
+      - name: Setup the latest .NET Core 3.1 SDK
+        if: matrix.framework == 'netcoreapp3.1'
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: 3.1.x
 
+      - name: Set test flavor
+        id: test-flavor
+        shell: bash
+        run: echo ::set-output name=flavor::$([[ "${{ matrix.os }}" == "cuda" ]] && echo "Cuda" || echo "CPU")
+
+      - name: Build and test
+        run: dotnet test --configuration=Release --framework=${{ matrix.framework }} -p:TreatWarningsAsErrors=true --logger GitHubActions Src/${{ matrix.library }}.Tests.${{ steps.test-flavor.outputs.flavor }}
+        env:
+          ILGPU_CLEAN_TESTS: ${{ github.event_name == 'schedule' || (github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))) }}
+
+  # Create the NuGet packages, with fixes for portable symbols.
   package:
     # Do not run this job for pull requests where both branches are from the same repo.
     # Jobs that depend on this one will be skipped too.
     # This prevents duplicate CI runs for our own pull requests, whilst preserving the ability to
     # run the CI for each branch push to a fork, and for each pull request originating from a fork.
-    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
+    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
     runs-on: windows-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
-      - name: Setup .NET Core SDK
+
+      - name: Setup the latest .NET 5 SDK
         uses: actions/setup-dotnet@v1
         with:
-          dotnet-version: 3.1.407
-      - name: Pin .NET Core SDK
-        run: dotnet new globaljson --sdk-version 3.1.407
+          dotnet-version: 5.0.x
+
       - name: Check version
         id: version
         run: |
@@ -212,9 +255,19 @@ jobs:
     outputs:
       tag: ${{ steps.version.outputs.version }}
 
-  publish-nuget-pre-release:
-    if: github.ref == 'refs/heads/master' && github.event.repository.fork == 'false'
-    needs: [check-style, build-and-test, package]
+  # Virtual job that can be configured as a required check before a PR can be
+  # merged.
+  all-required-checks-done:
+    needs: [check-style, build, test, package]
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo "All required checks done"
+
+  # Publish a preview version of the NuGet packages on feedz.io when there is
+  # a push to master.
+  publish-preview:
+    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.event.repository.fork == 'false'
+    needs: [all-required-checks-done]
     runs-on: ubuntu-latest
     steps:
       - name: Download NuGet package artifact
@@ -224,9 +277,12 @@ jobs:
       - name: Publish to FeedzIO
         run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.FEEDZIO_API_KEY }} --source https://f.feedz.io/ilgpu/preview/nuget/index.json
 
-  publish:
-    if: startsWith(github.ref, 'refs/tags/v') && github.event.repository.fork == 'false'
-    needs: [check-style, build-and-test, package]
+
+  # Create a GitHub release and publish the NuGet packages to nuget.org when
+  # a tag is pushed.
+  publish-release:
+    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.event.repository.fork == 'false'
+    needs: [all-required-checks-done]
     runs-on: ubuntu-latest
     steps:
       - name: Download NuGet package artifact
